// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuff.proto

package shared

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request user information
type UserInformationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInformationRequest) Reset()         { *m = UserInformationRequest{} }
func (m *UserInformationRequest) String() string { return proto.CompactTextString(m) }
func (*UserInformationRequest) ProtoMessage()    {}
func (*UserInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuff_8df5653b957f64a0, []int{0}
}
func (m *UserInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInformationRequest.Unmarshal(m, b)
}
func (m *UserInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInformationRequest.Marshal(b, m, deterministic)
}
func (dst *UserInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInformationRequest.Merge(dst, src)
}
func (m *UserInformationRequest) XXX_Size() int {
	return xxx_messageInfo_UserInformationRequest.Size(m)
}
func (m *UserInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInformationRequest proto.InternalMessageInfo

func (m *UserInformationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// The user information object
type UserInformation struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInformation) Reset()         { *m = UserInformation{} }
func (m *UserInformation) String() string { return proto.CompactTextString(m) }
func (*UserInformation) ProtoMessage()    {}
func (*UserInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuff_8df5653b957f64a0, []int{1}
}
func (m *UserInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInformation.Unmarshal(m, b)
}
func (m *UserInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInformation.Marshal(b, m, deterministic)
}
func (dst *UserInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInformation.Merge(dst, src)
}
func (m *UserInformation) XXX_Size() int {
	return xxx_messageInfo_UserInformation.Size(m)
}
func (m *UserInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInformation.DiscardUnknown(m)
}

var xxx_messageInfo_UserInformation proto.InternalMessageInfo

func (m *UserInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInformationRequest)(nil), "shared.UserInformationRequest")
	proto.RegisterType((*UserInformation)(nil), "shared.UserInformation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserInfo(ctx context.Context, in *UserInformationRequest, opts ...grpc.CallOption) (*UserInformation, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *UserInformationRequest, opts ...grpc.CallOption) (*UserInformation, error) {
	out := new(UserInformation)
	err := c.cc.Invoke(ctx, "/shared.UserService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUserInfo(context.Context, *UserInformationRequest) (*UserInformation, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shared.UserService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*UserInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shared.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuff.proto",
}

func init() { proto.RegisterFile("protobuff.proto", fileDescriptor_protobuff_8df5653b957f64a0) }

var fileDescriptor_protobuff_8df5653b957f64a0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0x4b, 0xd3, 0x03, 0xb3, 0x84, 0xd8, 0x8a, 0x33, 0x12, 0x8b, 0x52, 0x53,
	0x94, 0x34, 0xb8, 0xc4, 0x42, 0x8b, 0x53, 0x8b, 0x3c, 0xf3, 0xd2, 0xf2, 0x8b, 0x72, 0x13, 0x4b,
	0x32, 0xf3, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x32, 0x53, 0x94, 0x54, 0xb9, 0xf8, 0xd1, 0x54,
	0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x82, 0x15, 0x71, 0x06, 0x81, 0xd9, 0x46, 0xe1,
	0x5c, 0xdc, 0x20, 0x65, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x1e, 0x5c, 0xdc, 0xee,
	0xa9, 0x25, 0x30, 0x8d, 0x42, 0x72, 0x7a, 0x10, 0x7b, 0xf5, 0xb0, 0x5b, 0x2a, 0x25, 0x8e, 0x43,
	0x5e, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x70, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x8a,
	0xf4, 0x9f, 0xcb, 0x00, 0x00, 0x00,
}
